---
- name: Install packages using loop
  hosts: test
  become: true
  become_user: root
  tasks:
    - name: Loop through packages and install them
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - nginx
        - mysql
        - php

