node {
    try {
        stage('Checkout') {
            git url: 'https://github.com/thejk726/DevOps.git', branch: 'main'
        }
        
        stage('Provisioning') {
            dir('Jenkins/nodeapp'){
            sh 'npm install'
            }    
        }
        
        stage('Build') {
            dir('Jenkins/nodeapp'){
            sh 'npm run build || echo "[!] No build step defined..."'
        }
        }
        
        stage('Test') {
            dir('nodeapp'){
            sh 'npm test'
            }   
        }

        stage('Deploy to staging') {
            dir('nodeapp'){
            sh './deploy.sh'
            }
        }

        // Notify success
        mail(
            to: 'thejkiran726@gmail.com',
            subject: "Pipeline success! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Good news! The build ${env.JOB_NAME} #${env.BUILD_NUMBER} was successful!"
        )
        echo 'Pipeline successful!'
    } catch(Exception e) {
        // Notify failure
        mail(
            to: 'thejkiran726@gmail.com',
            subject: "Pipeline failed! ${env.JOB_NAME} #${env.BUILD_NUMBER}",
            body: "Unfortunately, the build ${env.JOB_NAME} #${env.BUILD_NUMBER} has failed!"
        )
        
        echo 'Pipeline failed!'
        currentBuild.result = 'FAILURE'
        throw e
    } finally {
        // Archive test results and artifacts
        archiveArtifacts artifacts: '**/nodeapp/**', allowEmptyArchive: true
        junit 'nodeapp/test-results.xml'
    }
}
