---
# Playbook to deploy the springapp on targets

- name: Deploy app on target hosts
  hosts: devservers
  become: yes
  become_user: thejkiran

  vars_files:
    - "{{ lookup('env','WORKSPACE') }}/assets/pringapp_assets.yml"

  roles:
#  - git_checkout
  - docker_build
  - docker_login
  - docker_push
