---
# Playbook to deploy the springapp on targets

- name: Deploy app on target hosts
  hosts: devservers
  remote_user: thejkiran
  become: yes
  become_user: root

  vars_files:
    - "{{ lookup('env','WORKSPACE') }}/springapp_assets.yml"

  roles:
#  - git_checkout
  - docker_build
  - docker_login
  - docker_push
