node {
    stage('Git Checkout') {
        withCredentials([string(credentialsId: 'git-url', variable: 'GIT_URL')]) {
            checkout([$class: 'GitSCM', branches: [[name: '*/main']], userRemoteConfigs: [[url: GIT_URL]],
            extensions: [[$class: 'CleanBeforeCheckout']]
            ])
        }
    }

    stage('Build') {
        dir('Project/springapp') {
            app = docker.build("thejk726/test-images:springapp-${BUILD_ID}")
        }
    }

    stage('Docker push') {
        withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER_NAME', passwordVariable: 'PASSWORD')]) {
            docker.withRegistry('https://registry.hub.docker.com', 'dockerhub-creds') {
                // Tagging and pushing the image with the correct format
                app.push()
            }
        }
    }
}

