---
- name: Install and configure MySQL and Java for dev and client servers
  hosts: all
  become: true
  become_user: root
  vars_files:
    - ./host_vars/dev_server_1.yml
    - ./host_vars/dev_server_2.yml
  roles:
    - java_install
    - maven_install
    - python_modules
    - mysql_install
    - mysql_configure
#    - remove_mysql

