---
- name: Install and configure MySQL and Java for dev and client servers
  hosts: client
  become: true
  become_user: root
  roles:
    - java_install
    - maven_install
    - python_modules
    - mysql_install
    - mysql_configure
#    - remove_mysql

