---
# tasks file for roles/python_modules

- name: Install pip(if not installed)
  apt:
    name: python3-pip
    state: present

- name: Install PyMySQL module
  pip:
    name: pymysql
    state: present
