---
# tasks file for roles/start
  - name: Copy jar file to deployment folder
    copy:
      src: ../../Jenkins/simpleapi/target/simpleapi.jar
      dest: "{{ deploy_directory }}/simpleapi.jar"

  - name: Execute the jar file
    shell: 'nohup java -jar {{ deploy_directory }}/simpleapi.jar --spring.config.location={{ deploy_directory }}/application.properties &'

