---
- name: Stop MySQL service
  ansible.builtin.service:
    name: mysql
    state: stopped
  ignore_errors: yes  # In case the service is already stopped

- name: Uninstall MySQL server
  ansible.builtin.package:
    name: mysql-server
    state: absent

- name: Uninstall MySQL client
  ansible.builtin.package:
    name: mysql-client
    state: absent

- name: Uninstall MySQL common files
  ansible.builtin.package:
    name: mysql-common
    state: absent

- name: Remove MySQL configuration files
  ansible.builtin.file:
    path: /etc/mysql
    state: absent
    recurse: yes

- name: Remove MySQL data directory
  ansible.builtin.file:
    path: /var/lib/mysql
    state: absent
    recurse: yes

- name: Remove MySQL log files
  ansible.builtin.file:
    path: /var/log/mysql
    state: absent
    recurse: yes

- name: Clean up any remaining MySQL-related packages
  ansible.builtin.shell: |
    apt-get autoremove -y
    apt-get autoclean
  args:
    warn: false

- name: Remove MySQL user and group (if they exist)
  ansible.builtin.user:
    name: mysql
    state: absent
  ignore_errors: yes

- name: Remove any MySQL related directories under /usr
  ansible.builtin.find:
    paths: /usr
    patterns: '*mysql*'
    recurse: yes
  register: mysql_dirs

- name: Remove found MySQL directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ mysql_dirs.files }}"
  when: mysql_dirs.matched > 0

